import type { CaseData } from '../types'

export const midnightMurder: CaseData = {
  id: 'midnight-murder',
  title: 'The Midnight Murder',
  description: 'A wealthy art collector found dead in his locked library. Five guests. One killer.',
  difficulty: 3,
  estimatedMinutes: 15,
  setting: 'A gothic mansion on a rainy English moor, 1952.',
  openingScene:
    `Rain hammers the windows of Ashworth Manor.\n\nLord Edmund Ashworth, 67, is dead in his locked library. A glass of brandy beside him. Five guests remain in the house. Nobody has left.\n\nYou have until dawn.\n\nExplore rooms, inspect evidence, interrogate suspects — then make your accusation.`,
  victim: { name: 'Lord Edmund Ashworth', age: 67, occupation: 'Art collector', causeOfDeath: 'Cyanide poisoning' },
  murdererIndex: 2,

  suspects: [
    {
      id: 0, name: 'Dr. Victor Crane', role: 'Family physician', emoji: '👨‍⚕️',
      keywords: ['crane', 'doctor', 'dr crane', 'physician', 'victor'],
      defaultResponse: `Dr. Crane adjusts his glasses for the third time.\n\n"I was in the billiard room until after midnight. Reading. Alone."\n\nHis voice is steady. His hands are not.\n\n"I heard nothing unusual until someone shouted that Lord Ashworth was dead."`,
      topics: [
        { label: 'Ask about the body', keywords: ['body', 'victim', 'found', 'dead'],
          response: `"I forced the library door at around quarter past midnight. He had been sitting in his chair. The brandy glass was still in his hand.\n\n"I am a physician. I know what cyanide smells like. I said nothing because I did not want to cause panic."`,
          revealsClueId: 1 },
        { label: 'Ask about the locked door', keywords: ['door', 'locked', 'library', 'forced'],
          response: `"The door was locked from the inside. There is no other exit. I cannot explain it.\n\n"I have been asking myself the same question all night."` },
        { label: 'Ask about his alibi', keywords: ['alibi', 'billiard', 'where', 'night'],
          response: `"Billiard room. East corridor, ground floor. I was alone — I cannot prove it.\n\n"I heard the piano around eleven fifteen. I assumed it was the Reverend."` },
      ],
    },
    {
      id: 1, name: 'James Ashworth', role: "Lord Ashworth's son", emoji: '🧔',
      keywords: ['james', 'ashworth', 'son', 'heir'],
      defaultResponse: `James leans against the wall with studied casualness.\n\n"I was in the garden. Smoking. The rain started around eleven and I came inside."\n\nHe does not look like a man in mourning.\n\n"Before you ask — yes, we had our differences. He was going to change the will. Again."`,
      topics: [
        { label: 'Ask about the will', keywords: ['will', 'money', 'inheritance'],
          response: `"He threatened to cut me out every few years. It was a game to him.\n\n"This time he meant it. He found out about my debts. That's all I'm saying without a solicitor present."` },
        { label: 'Ask about the garden', keywords: ['garden', 'cigarette', 'rain', 'outside'],
          response: `"I was near the east wall. Stone bench — you can still see the cigarette stubs if the rain hasn't washed them away."\n\nHe pulls out a cigarette box. Same brand.\n\n"I came inside when the rain got heavy. Quarter to midnight, maybe."`,
          revealsClueId: 4 },
        { label: 'Ask about his father', keywords: ['father', 'lord', 'relationship'],
          response: `"We argued after dinner. He said I'd never amount to anything. Standard.\n\n"I did not poison him. If I'd wanted him dead I'd have been a lot more patient about it."` },
      ],
    },
    {
      id: 2, name: 'Margaret Hale', role: 'Personal secretary', emoji: '👩',
      keywords: ['margaret', 'hale', 'secretary'],
      defaultResponse: `Margaret sits perfectly straight. Hands folded. Nothing about her is accidental.\n\n"I served Lord Ashworth his brandy at eleven o'clock, as I do every evening. I then retired to my room."\n\nShe speaks as if reading from a prepared statement.\n\n"I heard nothing after that."`,
      topics: [
        { label: 'Ask about the brandy', keywords: ['brandy', 'served', 'drink', 'decanter'],
          response: `"I poured one glass. Lord Ashworth preferred his brandy alone. I set it on the sideboard, as always."\n\nNot a flicker.\n\n"I did not touch the decanter after that."` },
        { label: 'Ask about her alibi', keywords: ['room', 'retired', 'midnight', 'alibi'],
          response: `"I was in my room from eleven o'clock. I read until half past, then I slept."\n\nShe holds your gaze without blinking.\n\nThe cook saw her in the kitchen at quarter to midnight. She does not mention this.` },
        { label: 'Confront: The Vienna note', keywords: ['vienna', 'note', 'letter'],
          requiresClueId: 3,
          response: `For a fraction of a second — barely a heartbeat — something moves behind her eyes.\n\n"I have no idea what you are referring to."\n\nShe smooths an invisible wrinkle from her skirt.\n\n"Lord Ashworth and I had a professional relationship. Nothing more."` },
        { label: 'Confront: Seen in kitchen', keywords: ['kitchen', 'cook', 'midnight'],
          requiresClueId: 11,
          response: `A pause, just slightly too long.\n\n"I may have gone downstairs for water. I don't recall precisely."\n\nShe does not change her expression.\n\n"Is that significant?"` },
        { label: 'Confront: Chemistry textbook', keywords: ['chemistry', 'textbook', 'cyanide', 'poison'],
          requiresClueId: 6,
          response: `"That book belongs to a former tenant. I simply never discarded it."\n\nFor the first time she looks away.\n\n"I have an interest in science. That is not a crime."` },
      ],
    },
    {
      id: 3, name: 'Reverend Doyle', role: 'Old friend & priest', emoji: '⛪',
      keywords: ['reverend', 'doyle', 'thomas', 'priest'],
      defaultResponse: `Reverend Doyle sits with his hands clasped on his knees. He looks like a man carrying something heavy.\n\n"Edmund and I were friends for forty years. I cannot believe—"\n\nHe stops. Swallows.\n\n"I was in the sitting room all evening. I heard the piano around eleven fifteen."`,
      topics: [
        { label: 'Ask about the piano', keywords: ['piano', 'music', 'heard'],
          response: `"Yes, someone was playing. A Chopin nocturne — quite beautifully."\n\nA long pause.\n\n"I do not play piano myself. I assumed it was one of the others."\n\nHe does not say who. He is covering for someone.`,
          revealsClueId: 8 },
        { label: 'Ask about Lord Ashworth', keywords: ['lord', 'ashworth', 'edmund', 'friend'],
          response: `"He sent me a note earlier in the week. He said he had uncovered something troubling. I should have taken it more seriously."` },
        { label: "Push: what is he hiding", keywords: ['hiding', 'secret', 'know', 'confession'],
          response: `"There are things said in confidence that I cannot repeat. Even now."\n\nHis hands tighten.\n\n"What I can tell you is that Edmund was frightened. He had been frightened for some weeks."` },
      ],
    },
    {
      id: 4, name: 'Clara Webb', role: 'Art appraiser', emoji: '🔍',
      keywords: ['clara', 'webb', 'appraiser'],
      defaultResponse: `Clara Webb is the only person in the house who seems genuinely surprised.\n\n"I was in the east wing all evening cataloguing the collection — over sixty pieces.\n\n"I noticed something odd about one of the paintings. I was going to mention it to him in the morning."`,
      topics: [
        { label: 'Ask about the paintings', keywords: ['painting', 'odd', 'collection', 'art'],
          response: `"One of the landscapes had been rehung recently — the dust marks were wrong. It was slightly crooked, which Lord Ashworth would never have permitted.\n\n"Something had been moved behind it."`,
          revealsClueId: 5 },
        { label: 'Ask about the east wing', keywords: ['east wing', 'corridor', 'evening'],
          response: `"I was there until nearly midnight.\n\n"I saw Margaret walking past around quarter to midnight heading toward the kitchen stairs. She didn't see me."` },
        { label: 'Ask about Margaret', keywords: ['margaret', 'secretary', 'hale'],
          response: `"She always made me uneasy. Too composed.\n\n"I've met a few people like that — usually they're either very good at their job or very good at hiding something. Or both."` },
      ],
    },
  ],

  rooms: [
    {
      id: 1, name: 'Library', emoji: '📚', tagline: 'Where the body was found.',
      keywords: ['library', 'study', 'crime scene', 'body'],
      unlockedByDefault: true,
      arrivalText: `You stand in the library.\n\nRain beats against the tall windows. Lord Ashworth lies slumped in his armchair, exactly where he was found.\n\nA brandy decanter gleams on the sideboard. The cold fireplace holds its ash. The desk is buried under papers.`,
      searchText: `You search the library methodically.\n\nThe room was locked from the inside — no hidden exit. Whatever happened here, the killer found another way.\n\nThe brandy decanter. The body. The desk. The fireplace. Each has something to say.`,
      inspectables: [
        { label: 'Examine Body', emoji: '🩸', keywords: ['body', 'victim', 'lord', 'ashworth', 'corpse'],
          response: `His lips are slightly blue. A faint smell of almonds — barely detectable.\n\nFine white ash dusts his left sleeve. Not fireplace ash. Too fine, too uniform. Someone burned something recently.\n\nHis right index finger has an ink stain. He was writing before he died.`,
          revealsClueId: 2 },
        { label: 'Inspect Decanter', emoji: '🥃', keywords: ['brandy', 'decanter', 'glass', 'drink'],
          response: `You hold the decanter to the light.\n\nA residue on the inner rim — a faint discolouration that does not belong. Potassium cyanide, or something very like it.\n\nOne glass was poured. The glass beside the body.`,
          revealsClueId: 1 },
        { label: 'Search Desk', emoji: '📜', keywords: ['desk', 'paper', 'papers', 'letter', 'note'],
          response: `The desk is a chaos of letters — but Lord Ashworth was meticulous. This chaos was created after his death. Someone searched his papers.\n\nWedged under the inkstand, you find something missed: a crumpled note in Lord Ashworth's hand.\n\n"I know what you did in Vienna. Meet me in the library at midnight. — E.A."`,
          revealsClueId: 3 },
        { label: 'Examine Fireplace', emoji: '🔥', keywords: ['fireplace', 'hearth', 'ash', 'fire'],
          response: `The fireplace is cold — never lit tonight.\n\nBut there is ash in the grate. Fine, white, papery ash. Recent. Someone burned documents here, and the ash has not yet fully settled.\n\nWhoever did this was in a hurry.` },
        { label: 'Search Sideboard', emoji: '🔎', keywords: ['sideboard', 'vial', 'bottle', 'hidden', 'behind'],
          response: `Behind the decanter, tucked into the corner of the shelf — a tiny glass vial.\n\nNo longer than your thumb. Empty, but not clean. Cyanide traces coat the inside.\n\nSomeone put it here in haste.`,
          revealsClueId: 9 },
      ],
    },
    {
      id: 2, name: 'Kitchen', emoji: '🍳', tagline: 'Stone floors. The cook\'s domain.',
      keywords: ['kitchen', 'cook', 'cellar'],
      unlockedByDefault: true,
      arrivalText: `The kitchen is stone-floored and cold.\n\nMrs. Briggs — the cook — sits at the large table with a cup of tea, looking shaken. A small door in the corner leads to the cellar.`,
      searchText: `The kitchen smells of roast and old wood.\n\nMrs. Briggs watches you suspiciously. The cellar door is slightly ajar — the lock looks recently damaged.`,
      inspectables: [
        { label: 'Speak to the Cook', emoji: '👩‍🍳', keywords: ['cook', 'briggs', 'mrs briggs', 'woman'],
          response: `Mrs. Briggs sets down her tea.\n\n"I was here all evening. I don't go upstairs after dinner — not my place."\n\nShe pauses, then decides to tell you.\n\n"Miss Hale came down at quarter to midnight. Asked which brandy Lord Ashworth preferred. I told her the cognac. He always had the cognac."\n\nShe folds her hands.\n\n"She already knew that. She's been here three years."`,
          revealsClueId: 11 },
        { label: 'Inspect Cellar Door', emoji: '🚪', keywords: ['cellar', 'door', 'lock', 'broken'],
          response: `The cellar bolt has been forced — from the inside out.\n\nSomeone locked themselves in and broke the lock to get out. The cellar smells faintly of chemicals. Sharp and medicinal.`,
          revealsClueId: 10 },
      ],
    },
    {
      id: 3, name: 'Garden', emoji: '🌿', tagline: 'Rain-soaked. Someone was out here.',
      keywords: ['garden', 'outside', 'yard', 'lawn'],
      unlockedByDefault: true,
      arrivalText: `Rain hammers the garden.\n\nA stone bench sits near the east wall. The lawn is soft and sodden. Three cigarette stubs lie near the bench, already softening in the rain.`,
      searchText: `The ground near the east wall is churned — someone stood here for some time.\n\nThree cigarette stubs. Same brand. And near the base of the ivy wall: a small recess, recently disturbed.`,
      inspectables: [
        { label: 'Examine Cigarette Stubs', emoji: '🚬', keywords: ['cigarette', 'stub', 'tobacco'],
          response: `Three stubs, same brand — Craven A. The tobacco is fresh, smoked within the last few hours.\n\nYou have seen this cigarette box before. In James Ashworth's coat pocket.`,
          revealsClueId: 4 },
        { label: 'Inspect Stone Bench', emoji: '🪨', keywords: ['bench', 'stone', 'seat'],
          response: `A faint impression in the soil — someone stood here, pacing, for some time.\n\nThe position gives a partial view of the east wing windows and the library. Someone could have watched from here.` },
        { label: 'Search Ivy Wall', emoji: '🌿', keywords: ['wall', 'ivy', 'rose'],
          response: `The ivy near the base has been disturbed — pulled aside recently. Behind it: a small recess in the stone. Empty now.\n\nWhatever was hidden here is gone.` },
      ],
    },
    {
      id: 4, name: 'East Wing', emoji: '🖼️', tagline: 'Paintings floor to ceiling.',
      keywords: ['east wing', 'east', 'corridor', 'gallery', 'paintings'],
      unlockedByDefault: true,
      arrivalText: `The east wing corridor stretches before you, lined with paintings on both sides.\n\nClara Webb's cataloguing materials — notebooks, a magnifying glass — are set up at the far end.\n\nOne painting near the middle hangs slightly crooked.`,
      searchText: `You work down the corridor methodically.\n\nMost paintings are exactly as they should be — dust lines intact, hanging level. Except the landscape near the middle. Its dust marks are wrong. It was recently moved.`,
      inspectables: [
        { label: 'Examine Crooked Painting', emoji: '🖼️', keywords: ['painting', 'landscape', 'crooked', 'moved'],
          response: `You lift the landscape from its hook.\n\nBehind it: a wall safe, recessed into the plaster. The combination dial wiped clean of fingerprints.\n\nThe safe is open. It is empty.\n\nWhatever Lord Ashworth kept here is gone.`,
          revealsClueId: 5 },
        { label: 'Check Clara\'s Notes', emoji: '📒', keywords: ['clara', 'notes', 'notebook', 'catalogue'],
          response: `Clara's notebook lists sixty-one paintings. Against three she has written "provenance unclear" and circled in red.\n\nAll three are attributed to the same Parisian dealer. The same dealer appears in burned correspondence downstairs.` },
      ],
    },
    {
      id: 5, name: 'Sitting Room', emoji: '🎹', tagline: 'Someone played piano tonight.',
      keywords: ['sitting room', 'sitting', 'lounge', 'piano'],
      unlockedByDefault: true,
      arrivalText: `The sitting room is warm — or it was, before tonight.\n\nA grand piano stands against the far wall, lid open. Sheet music is open on the stand. A half-finished cup of tea on the side table.`,
      searchText: `The piano has been played recently — fresh finger marks in the fine dust on the keys.\n\nThe armchair by the fire is indented. A cold cup of tea. Whoever sat here was too agitated to eat — two biscuits untouched.`,
      inspectables: [
        { label: 'Examine Sheet Music', emoji: '🎵', keywords: ['piano', 'music', 'sheet', 'chopin'],
          response: `A Chopin nocturne, Op. 9 No. 2. The pages are dog-eared — this pianist knew this music well.\n\nIn the margin, in pencil: "For E. — Vienna, 1938."\n\nThe handwriting is precise and controlled. You have seen it before.`,
          revealsClueId: 8 },
        { label: 'Inspect Teacup', emoji: '☕', keywords: ['tea', 'cup', 'cold'],
          response: `Stone cold. Made hours ago.\n\nTwo biscuits remain on the saucer, untouched. Whoever sat here was too agitated to eat.` },
      ],
    },
    {
      id: 6, name: "Margaret's Room", emoji: '🛏️', tagline: 'Almost aggressively neat.',
      keywords: ["margaret's room", 'margaret room', 'bedroom', 'her room', 'upstairs'],
      unlockedByDefault: false,
      unlocksAfterClueId: 11,
      arrivalText: `Margaret Hale's room is almost aggressively neat.\n\nThe bed made with military precision. A leather briefcase just visible under the bed. A single book on the nightstand.\n\nA train ticket protrudes from a coat in the open wardrobe. Departure: tomorrow morning.`,
      searchText: `The room resists you. Everything in its place.\n\nBut neatness can be its own form of concealment. The briefcase. The book. The wardrobe. Each one is a question.`,
      inspectables: [
        { label: 'Open Briefcase', emoji: '💼', keywords: ['briefcase', 'case', 'bag', 'leather'],
          response: `The briefcase is unlocked.\n\nInside: provenance certificates for three paintings — the same three Clara flagged. Convincing forgeries. The signature of a Paris dealer who died in 1941.\n\nMargaret Hale's fingerprints are on every page.`,
          revealsClueId: 7 },
        { label: 'Read the Textbook', emoji: '📖', keywords: ['book', 'textbook', 'chemistry', 'reading'],
          response: `A toxicology textbook. Graduate level.\n\nChapter 11: Cyanide Compounds. The margins are dense with annotations in a precise, controlled hand. One note reads:\n\n"undetectable at this concentration if body found within 2hrs?"`,
          revealsClueId: 6 },
        { label: 'Check Train Ticket', emoji: '🎫', keywords: ['ticket', 'train', 'wardrobe', 'coat'],
          response: `London Victoria. First class.\n\nDeparture: tomorrow morning, 6:42am.\n\nShe was planning to leave before the investigation began.` },
      ],
    },
  ],

  clues: [
    { id: 1, name: 'Cyanide in decanter', description: 'Potassium cyanide residue on the inner rim. Only one glass was poured.', roomId: 1, linkedSuspectIds: [2] },
    { id: 2, name: 'Ash on victim\'s sleeve', description: 'Fine white ash — burned paper, not fireplace ash. Someone destroyed documents near the body.', roomId: 1, linkedSuspectIds: [] },
    { id: 3, name: 'The midnight note', description: '"I know what you did in Vienna. Meet me in the library at midnight. — E.A."', roomId: 1, linkedSuspectIds: [2] },
    { id: 4, name: 'Cigarette stubs', description: "Three Craven A stubs by the garden bench. Same brand as James Ashworth's.", roomId: 3, linkedSuspectIds: [1] },
    { id: 5, name: 'Emptied wall safe', description: 'Safe hidden behind a recently moved painting. Open. Empty. Combination wiped clean.', roomId: 4, linkedSuspectIds: [2] },
    { id: 6, name: 'Chemistry textbook', description: "Margaret's toxicology textbook — annotated with notes about undetectable cyanide concentrations.", roomId: 6, linkedSuspectIds: [2] },
    { id: 7, name: 'Forged documents', description: "Forged provenance certificates in Margaret's briefcase. Her fingerprints on every page.", roomId: 6, linkedSuspectIds: [2] },
    { id: 8, name: 'Sheet music inscription', description: '"For E. — Vienna, 1938." The handwriting in the piano margin matches Margaret\'s.', roomId: 5, linkedSuspectIds: [2] },
    { id: 9, name: 'Empty cyanide vial', description: 'Tiny glass vial hidden behind the brandy decanter. Cyanide traces inside.', roomId: 1, linkedSuspectIds: [2] },
    { id: 10, name: 'Broken cellar lock', description: 'Cellar bolt forced from inside. Smells of chemicals.', roomId: 2, linkedSuspectIds: [] },
    { id: 11, name: "Cook's testimony", description: "Mrs. Briggs saw Margaret in the kitchen at 11:45pm — asking which brandy Lord Ashworth preferred, despite knowing for 3 years.", roomId: 2, linkedSuspectIds: [2] },
  ],

  timeline: [
    { time: '10:00pm', event: 'Dinner ends. Lord Ashworth retires to the library.' },
    { time: '11:00pm', event: 'Margaret serves brandy to Lord Ashworth.' },
    { time: '11:15pm', event: 'Piano heard in the sitting room.' },
    { time: '11:45pm', event: 'Margaret seen in kitchen by the cook.' },
    { time: '12:00am', event: 'Lord Ashworth found dead. Library locked from inside.' },
    { time: '12:05am', event: 'Dr. Crane forces the door.' },
  ],

  insights: [
    { id: 'two-cyanide-sources', requiresClueIds: [1, 9],
      text: '⚗️ Two cyanide traces: residue in the decanter AND a hidden vial behind it. This murder was planned days in advance — not a moment of passion.' },
    { id: 'vienna-connection', requiresClueIds: [3, 8],
      text: '🎹 The midnight note mentions Vienna. The piano sheet music reads "For E. — Vienna, 1938." The same past connects Lord Ashworth and the pianist. They knew each other there.' },
    { id: 'margaret-lies', requiresClueIds: [6, 11],
      text: "⚠️ Margaret's textbook covers undetectable cyanide doses. Mrs. Briggs saw her in the kitchen at 11:45pm asking which brandy he preferred — she already knew. She was building an alibi." },
    { id: 'forgery-motive', requiresClueIds: [5, 7],
      text: '🖼️ The forged provenance documents explain the empty safe. She sold fake certificates for stolen paintings. Lord Ashworth discovered it. That is what the midnight note was about.' },
    { id: 'james-cleared', requiresClueIds: [4],
      text: "🚬 James's cigarette stubs confirm he was in the garden all evening. He has motive (the will) but no access to cyanide and no opportunity." },
    { id: 'full-picture', requiresClueIds: [3, 6, 7, 8, 11],
      text: '🔍 Vienna. Forgeries. Chemistry. Lies. Everything converges on one person. She had motive, means, and twelve years of practice at deception.' },
  ],
}
